<?php

$apiLog = $block->getApiLogEntry();

?>
<?php if (!$apiLog): ?>
    <?php echo __('The requested API-Log entry is not existing!'); ?>
<?php else: ?>
    <div data-mage-init='{"floatingHeader": {}}' class="page-actions"><?php echo $block->getButtonsHtml() ?></div>
    <section class="admin__page-section  order-view-account-information">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-information">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __('Request'); ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <tbody>
                        <?php foreach ($apiLog->getRequestDetails() as $key => $value): ?>
                            <tr>
                                <th><?php echo $key; ?></th>
                                <td><?php echo $value; ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <?php if (!empty($apiLog->getResponseDetails())): ?>
                <div class="admin__page-section-item order-account-information">
                    <div class="admin__page-section-item-title">
                        <span class="title"><?php echo __('Response'); ?></span>
                    </div>
                    <div class="admin__page-section-item-content">
                        <table class="admin__table-secondary order-account-information-table">
                            <tbody>
                            <?php foreach ($apiLog->getResponseDetails() as $key => $value): ?>
                                <tr>
                                    <th><?php echo $key; ?></th>
                                    <td><?php echo $value; ?></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </section>
<?php endif; ?>
